article/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<article_id>[0-9]+)/$', views.detail, name = 'article_detail'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.archive, name = 'article_archive'),
    url(r'^post_comment/$', views.post_comment, name = 'post_comment'),
    url('', views.index, name = 'article_list'),
]

farewell/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^article/', include('article.urls')),
    url(r'^archive/', include('article.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns.append(url(r'', views.home, name = 'home'))

article/models.py
from django.db import models
from django.utils.html import format_html
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from accessor.models import Accessor

import time

class Category(models.Model):
    category_name = models.CharField(max_length = 20)
    category_desc = models.TextField(max_length = 100)
    last_updated = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return self.category_name
        
    class Meta:
        verbose_name = '文章分类'
        verbose_name_plural = '文章分类'

class Article(models.Model):
    PUB_STATE = 10
    DRAFT_STATE = 11
    HIDEN_STATE = 12

    ARTICLES_STATES = (
        (PUB_STATE, '已发布'),
        (DRAFT_STATE, '草稿'),
        (HIDEN_STATE, '隐藏'),
    )

    title = models.CharField("标题", max_length = 30)
    subhead = models.CharField("副标题", max_length = 50)
    category = models.ForeignKey(Category, on_delete = models.SET_NULL, verbose_name = "分类", null = True)
    tags = models.CharField("标签", max_length = 30)
    read_count = models.PositiveIntegerField("阅读量", default = 2)
    pub_date = models.DateTimeField("发布时间", auto_now_add = True)
    last_updated = models.DateTimeField("最后更新时间", auto_now = True)
    summary = RichTextField(config_name='custom', verbose_name = '摘要', default = '')
    context = RichTextUploadingField(config_name='default', verbose_name = '正文')
    state = models.PositiveSmallIntegerField(
        verbose_name = '状态',
        choices = ARTICLES_STATES, 
        default = PUB_STATE,
    )
    
    def __str__(self):
        return self.title
    
    def is_published(self):
        return self.state == self.PUB_STATE
        
    def is_hiden(self):
        return self.state == self.HIDEN_STATE
        
    def is_draft(self):
        return self.state == self.DRAFT_STATE
    
    def color_state(self):
        if self.is_published:
            color = 'green'
        elif self.is_hiden:
            color = 'red'
        else:
            color = 'gray'
        
        state_desc = '草稿'
        for s in self.ARTICLES_STATES:
            if s[0] == self.state:
                state_desc = s[1]
        
        return format_html(
            '<span style="color: {};">{}</span>',
            color,
            state_desc
        )
    color_state.short_description = '状态'
    
    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'
    
class ArticleComment(models.Model):
    STATE_SHOW = False
    STATE_HIDEN = True
    
    COMMENT_STATE = (
        (STATE_SHOW, '显示'),
        (STATE_HIDEN, '隐藏'),
    )
    
    TYPE_ACK_ARTICLE = 1
    TYPE_ACK_COMMENT = 2

    article = models.ForeignKey(Article, on_delete = models.CASCADE, editable = False)
    state = models.BooleanField(
        choices = COMMENT_STATE,
        default = STATE_HIDEN,
    )
    comment = models.TextField("评论正文")
    comment_type = models.PositiveSmallIntegerField(editable = False, default = TYPE_ACK_ARTICLE)
    parent_id = models.IntegerField(default = 0, editable = False)
    pub_time = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(Accessor)
    
    def __str__(self):
        return str(self.id)
    
    def is_show(self):
        return self.state == self.STATE_SHOW
        
    def is_hiden(self):
        return self.state == self.STATE_HIDEN
        
    def is_ack_article(self):
        return self.comment_type == self.TYPE_ACK_ARTICLE
        
    def is_ack_comment(self):
        return self.comment_type == self.TYPE_ACK_COMMENT
        
    class Meta:
        verbose_name = '文章评论'
        verbose_name_plural = '文章评论'    
    
    @classmethod
    def create_comment(cls, article, comment, parent_id, user):
        co = cls(article = article, comment = comment, parent_id = parent_id, user = user)
        co.save()
        return co
        

article/forms.py
from django import forms

from accessor.models import Accessor

class CommentForm(forms.Form):
    article_id = forms.IntegerField()
    comment_parent_id = forms.IntegerField()
    email = forms.CharField(max_length = 30)
    username = forms.CharField(max_length = 30)
    website = forms.CharField(max_length = 40, required = False)
    comment = forms.CharField(max_length = 1000)
    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        email = cleaned_data.get("email")
        username = cleaned_data.get("username")
        email_obj = Accessor.objects.filter(email = email)
        if email_obj.exists() == False:
            name_obj = Accessor.objects.filter(name = username)
            if name_obj.exists() == True:
                raise forms.ValidationError("昵称%s已被注册, 更换一个喽" % username)
            Accessor.create_accessor(email, username, cleaned_data.get("website"))
        else:
            obj = email_obj[0]
            obj.name = username
            obj.website = cleaned_data.get("website")
            obj.save()
        return cleaned_data

article/views.py
from datetime import datetime
from dateutil.relativedelta import relativedelta
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.http import Http404

from .models import *
from .forms import CommentForm
from accessor.models import Accessor


def index(request):
    latest_article_list = Article.objects.order_by('-pub_date')[:7]
    template = loader.get_template('articles/index.html')
    context = {
        'latest_article_list': latest_article_list,
        'archive_list': get_archives()
    }
    return HttpResponse(template.render(context, request))
    
def detail(request, article_id):
    try:
        article = Article.objects.get(pk = article_id)
        form = CommentForm()
        comment_list = ArticleComment.objects.filter(article = article).order_by('-pub_time')[:10]
        previous_articles = Article.objects.filter(pub_date__gt = article.pub_date).order_by('pub_date')[:1]
        next_articles = Article.objects.filter(pub_date__lt = article.pub_date).order_by('-pub_date')[:1]
    except:
        raise Http404('迷路了, 招贴寻人启事')
        
    data = {
            'article' : article, 
            'form': form, 
            'comment_list' : comment_list, 
            'archive_list': get_archives(),
        }
    
    if len(previous_articles) > 0:
        data['previous_article'] = previous_articles[0]
        
    if len(next_articles) > 0:
        data['next_article'] = next_articles[0]
    
    return render(request, 'articles/detail.html', data)

def archive(request, year, month):
    begin_date = datetime.strptime('%s-%s-%s' % (year, month, '01'), '%Y-%m-%d')
    end_date = begin_date + relativedelta(months = +1)
    article_list = Article.objects.filter(pub_date__gte = begin_date).filter(pub_date__lt = end_date).order_by('-pub_date')[:7]
    template = loader.get_template('articles/index.html')
    context = {
        'latest_article_list': article_list,
        'archive_list': get_archives()
    }
    return HttpResponse(template.render(context, request))
    
def post_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            article_id = form.cleaned_data['article_id']
            article = Article.objects.get(pk = article_id)
            user = Accessor.objects.get(email = form.cleaned_data['email'])
            article_comment = ArticleComment.create_comment(article, form.cleaned_data['comment'], form.cleaned_data['comment_parent_id'], user)
            article_comment.save()
            return redirect('/article/%s/' % article_id)
    return HttpResponse(form.errors.as_data())
    
def get_archives():
    from django.db.models.functions import TruncMonth
    from django.db.models import Count
    archive_list = Article.objects.annotate(month = TruncMonth('pub_date')).values('month').annotate(c = Count('id')).values('month', 'c')
    r = []
    for archive in archive_list:
        r.append(("%s年%s月" % (archive['month'].year, archive['month'].month), archive['month'].year, archive['month'].month, archive['c']))
    return r

article/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% load static %}
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/prism.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <style type="text/css">
    img, a img {
        border:0;
        margin:0;
        padding:0;
        max-width:600px;
        width: expression(this.width > 600 ? 600px : 'auto';);
        max-height:360px;
        height: expresion(this.height > 360 ? 360px : 'auto';);
    }
    </style>
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item" href="/">首页</a>
          <a class="blog-nav-item" href="/article/">文章</a>
          <a class="blog-nav-item" href="/">关于</a>
        </nav>
      </div>
    </div>

    <div class="container">
      {% include 'articles/header.html' %}
      <div class="row">
        <div class="col-sm-8 blog-main">
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{{ article_detail }}">{{ article.title }}</a></h2>
                <p class="blog-post-meta">标签: {{ article.tags}} | 分类: {{ article.category }} | {{article.pub_date }}</p>
                <p>{{ article.context|safe }}</p>
                <hr/>
            </div>

        <div id="comment-area" class="comment-post">
            {% if comment_list %}
                {% for comment in comment_list %}
                    <p><span><strong>{{ comment.user.name }}</strong></span> <span>{{ comment.pub_time }}</span></p>
                    <p>{{ comment.comment|safe }}</p>
                    <hr/>
                {% endfor %}
            {% endif %}
            <h4 id="reply-title" class="comment-reply-title">发表评论</h4>
                <form action="/article/post_comment/" method="post" id="commentform" class="comment-form">
                    {% csrf_token %}
                    <p class="comment-notes"><span id="email-notes">电子邮件地址不会被公开。</span> 必填项已用<span class="required">*</span>标注</p>
                    <p><label for="comment">评论<span class="required">*</span></label><br/>
                        <textarea id="id_comment" name="comment" cols="50" rows="6" maxlength="1000" required="true"></textarea>
                    </p>
                    <p class="comment-form-author"><label for="author">昵称<span class="required">*</span></label><br/>
                        <input id="id_username" name="username" type="text" size="40" maxlength="30" required="true"/>
                    </p>
                    <p class="comment-form-email"><label for="email">电子邮件<span class="required">*</span></label><br/>
                        <input id="id_email" name="email" type="text" value="" size="40" maxlength="30" required='true'/>
                    </p>
                    <p class="comment-form-website"><label for="website">网址</label><br/>
                        <input id="id_website" name="website" type="text" value="" size="40" maxlength="40"/>
                    </p>
                    <p class="form-submit"><input name="submit" type="submit" id="id_submit" value="发表评论"/>
                        <input type='hidden' name='article_id' value={{ article.id }} id='id_article_id'/>
                        <input type='hidden' name='comment_parent_id' value='0' id='id_comment_parent_id'/>
                    </p>
                </form>
            <hr/>
        </div>

          <nav>
            <ul class="pager">
              {% if previous_article %}
                <li><a href="/article/{{ previous_article.id }}/">上一篇</a></li>
              {% endif %}
              {% if next_article %}
                <li><a href="/article/{{ next_article.id }}/">下一篇</a></li>
              {% endif %}
            </ul>
          </nav>

        </div>

        {% include 'articles/sider.html' %}
      </div><!-- /.row -->
    </div><!-- /.container -->
    {% include 'articles/footer.html' %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

article/templates/articles/footer.html
<!DOCTYPE html>
<html lang="en">
  <body>
    <footer class="blog-footer">
      <p>Build By <a href="http://www.djangoproject.com/">Django</a></p>
      <p>Template From <a href="http://getbootstrap.com">Bootstrap</a></p>
      <p><a href="#">Back to top</a></p>
    </footer>
  </body>
</html>

article/templates/articles/header.html
<!DOCTYPE html>
<html lang="en">
    <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
    </div>
</html>

article/templates/articles/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/">首页</a>
          <a class="blog-nav-item" href="/article/">文章</a>
          <a class="blog-nav-item" href="/">关于</a>
        </nav>
      </div>
    </div>

    <div class="container">
      {% include 'articles/header.html' %}
      <div class="row">
        <div class="col-sm-8 blog-main">
            {% if latest_article_list %}
                {% for article in latest_article_list %}
                    <div class="blog-post">
                        <h2 class="blog-post-title"><a href="/article/{{ article.id }}/">{{ article.title }}</a></h2>
                        <p class="blog-post-meta">标签: {{ article.tags}} | 分类: {{ article.category }} | {{article.pub_date }}</p>
                        <p>{{ article.summary|safe }}</p>
                        <hr>
                    </div>
                {% endfor %}
            {% else %}
                <p>No articles are available.</p>
            {% endif %}

           <div class="more">
                <p><a href="#">更多文章...</a></p>
           </div>
        </div>

        {% include 'articles/sider.html' %}
      </div><!-- /.row -->
    </div><!-- /.container -->
    {% include 'articles/footer.html' %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

article/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item" href="/">首页</a>
          <a class="blog-nav-item active" href="/article/">文章</a>
          <a class="blog-nav-item" href="/">关于</a>
        </nav>
      </div>
    </div>

    <div class="container">
      {% include 'articles/header.html' %}
      <div class="row">
        <div class="col-sm-8 blog-main">
            {% if latest_article_list %}
                {% for article in latest_article_list %}
                    <div class="blog-post">
                        <h2 class="blog-post-title"><a href="/article/{{ article.id }}/">{{ article.title }}</a></h2>
                        <p class="blog-post-meta">标签: {{ article.tags}} | 分类: {{ article.category }} | {{article.pub_date }}</p>
                        <p>{{ article.summary|safe }}</p>
                        <hr>
                    </div>
                {% endfor %}
            {% else %}
                <p>No articles are available.</p>
            {% endif %}
           
           <div class="more">
                <p><a href="#">更多文章...</a></p>
           </div>
        </div>
        
        {% include 'articles/sider.html' %}
      </div><!-- /.row -->
    </div><!-- /.container -->
    {% include 'articles/footer.html' %}
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

article/templates/articles/sider.html
<!DOCTYPE html>
<html lang="en">
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        <h4>标签</h4>
        <p>互联网 旅行 历史 摄影 Django</p>
      </div>
      <div class="sidebar-module">
        <h4>归档</h4>
        <ol class="list-unstyled">
            {% if archive_list %}
                {% for archive, year, month, count in archive_list %}
                    <li><a href="/archive/{{ year }}/{{ month }}">{{ archive }}({{ count }})</a></li>
                {% endfor %}
            {% endif %}
        </ol>
      </div>
      <div class="sidebar-module">
        <h4>链接</h4>
        <ol class="list-unstyled">
          <li><a href="https://github.com/Alex2Apple">GitHub</a></li>
        </ol>
      </div>
    </div><!-- /.blog-sidebar -->
</html>